"use client";

import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import '../styles/globals.css';



async function getQuestions() {
    const res = await fetch('api/questions');
    return res.json();
}

export default function HomePage() {
    const [questionFilter, setQuestionFilter] = useState([]);
    const [questions, setQuestions] = useState<any[]>([]);

    const handleClick = async () => {
        if (questions.length == 0) {
            const data = await getQuestions();
            setQuestions(data)
            setQuestionFilter(data.sort(() => Math.random() - 0.5)[0].question)
        } else if (questions.length !== 0) {
            setQuestionFilter(questions.sort(() => Math.random() - 0.5)[0].question)
        }
    }
    return (
        <div>
            <Head>
                <title>Random Interview Question</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="p-4 flex-grow">
                <section className="bg-white dark:bg-gray-900">
                    <div className="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
                        <div className="mx-auto max-w-screen-sm text-center">
                            <h2 className="mb-4 text-4xl tracking-tight font-extrabold leading-tight text-gray-900 dark:text-white">Show here question</h2>
                            <div>{questions && <p className="mb-6 font-light text-gray-400 dark:text-gray-300 md:text-lg">{questionFilter} </p>}</div>
                            <button className="py-2 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75" onClick={handleClick}>
                                Generate Question
                            </button>
                        </div>
                    </div>
                </section>

            </main>
        </div>
    )
}
