"use client";

import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'


async function getQuestions() {
    const res = await fetch('api/questions');
    return res.json();
}

export default function HomePage() {
    const [questionFilter, setQuestionFilter] = useState([]);
    const [questions, setQuestions] = useState<any[]>([]);

    const handleClick = async () => {
        if (questions.length == 0) {
            const data = await getQuestions();
            setQuestions(data)
            setQuestionFilter(data.sort(() => Math.random() - 0.5)[0].question)
        } else if (questions.length !== 0) {
            setQuestionFilter(questions.sort(() => Math.random() - 0.5)[0].question)
        }
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <p className={styles.description}>
                    Show here question
                </p>
                {questions && <p>{questionFilter} </p>}
                <button onClick={handleClick}>
                    Generate Question
                </button>
            </main>
        </div>
    )
}
