import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

async function getQuestions() {
  const res = await fetch('api/questions');
  return res.json();
}
async function getGifts(param:string) {
  const res = await fetch(`https://api.giphy.com/v1/gifs/search?api_key=AaxWvWC73WGuQetWmy5EY9lWpOdzoYSA&q=${param}&limit=5&offset=0&rating=g&lang=en`);
  https://api.giphy.com/v1/videos/search?${param}q=&limit=20&api_key=Gc7131jiJuvI7IdN0HZ1D7nh0ow5BU6g&pingback_id=184451b5589f8d94
  return res.json();
}

export default function Home() {
  const [questions, setQuestions] = useState([]);
  const [gif, setGif] = useState('')
  
  const handleClick = async () => {
    const data = await getQuestions();
    setQuestions(data.sort(() => Math.random() - 0.5)[0].question)
    console.log(data.sort(() => Math.random() - 0.5)[0].question.split(" ")[0])
    const gif = await getGifts(data.sort(() => Math.random() - 0.5)[0].question);
    setGif(gif.data[0].images.original.url)
     console.log(gif)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={styles.description}>
          Show here question
        </p>
        {questions && <p>{questions} </p>}
        <span>
          {
            gif && <img src={gif} alt="gif" /> ? <img src={gif} alt="gif" /> : <p>loading...</p>
          }
        </span>
        <button onClick={handleClick}>
          Generate Question
        </button>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Matias Fandiño
        </a>
      </footer>
    </div>
  )
}
